# Generated by Django 6.0.4 on 2026-04-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('postnom', models.CharField(max_length=30)),
                ('pren', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('lieuN', models.CharField(max_length=20)),
                ('datNais', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mont', models.FloatField()),
                ('unitMon', models.CharField(max_length=10)),
                ('motif', models.CharField(max_length=30)),
                ('datPaie', models.DateField()),
                ('Et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplWeb.etudiant')),
            ],
        ),
    ]
