# Generated by Django 6.0.4 on 2026-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mont',
            field=models.IntegerField(),
        ),
    ]
